{"prompt": "fix: throw bad request while pushing duplicate data to redis (#3016)", "response": "Files to modify:\n\n\n**utils.rs**\n  Add:\n    - function: private::to_redis_failed_response\n    - trait: pub::RedisErrorExt\n    - impl: impl RedisErrorExt for error_stack::Report<errors::RedisError>\n\n**refund.rs**\n  Modify existing code\n\n**reverse_lookup.rs**\n  Modify existing code\n\n**db_utils.rs**\n  Modify existing code\n\n**errors.rs**\n  Add:\n    - function: private::to_redis_failed_response\n    - trait: pub::RedisErrorExt\n    - impl: impl RedisErrorExt for error_stack::Report<RedisError>\n\n**lookup.rs**\n  Modify existing code\n\n**payment_attempt.rs**\n  Modify existing code\n\n**payment_intent.rs**\n  Modify existing code\n\n**utils.rs**\n  Add:\n    - function: private::to_redis_failed_response\n    - trait: pub::RedisErrorExt\n    - impl: impl RedisErrorExt for error_stack::Report<errors::RedisError>"}
